"""
Portfolio data for Santiago Sabadini.
Edit this file to update your portfolio content.
"""

profile = {
    "name": "Santiago Sabadini",
    "nickname": "Santi",
    "title": "Python Developer & AI Enthusiast",
    "location": "Bahía Blanca, Argentina",
    "education": "Tecnicatura Universitaria en Programación — UTN",
    "bio": (
        "Desarrollador enfocado en Python, C# e Inteligencia Artificial. "
        "Estudiante de la Tecnicatura Universitaria en Programación en la UTN. "
        "Me especializo en integrar IA para optimizar código, revisar arquitectura "
        "y validar lógica generada por modelos de lenguaje. "
        "Siempre buscando aprender y construir soluciones que tengan impacto real."
    ),
    "bio_en": (
        "Developer focused on Python, C# and Artificial Intelligence. "
        "Currently studying at UTN (Universidad Tecnológica Nacional). "
        "I specialize in integrating AI to optimize code, review architecture "
        "and validate logic generated by language models. "
        "Always looking to learn and build solutions with real-world impact."
    ),
    "avatar_url": None,
    "resume_url": None,
}

projects = [
    {
        "id": 1,
        "title": "Car Maintenance Tracker",
        "description": (
            "Aplicación en Python para el seguimiento completo de mantenimiento vehicular. "
            "Permite registrar servicios, recordatorios y llevar un historial detallado."
        ),
        "description_en": (
            "Python application for complete vehicle maintenance tracking. "
            "Register services, set reminders, and keep a detailed maintenance history."
        ),
        "tech": ["Python"],
        "github_url": "https://github.com/santiagosabadini",
        "live_url": None,
        "featured": True,
    },
    {
        "id": 2,
        "title": "Music Discord Bot",
        "description": (
            "Bot funcional para Discord que permite reproducir música en canales de voz. "
            "Comandos intuitivos para buscar, reproducir y gestionar colas de reproducción."
        ),
        "description_en": (
            "Functional Discord bot for playing music in voice channels. "
            "Intuitive commands to search, play and manage playback queues."
        ),
        "tech": ["Python", "Discord.py"],
        "github_url": "https://github.com/santiagosabadini",
        "live_url": None,
        "featured": True,
    },
    {
        "id": 3,
        "title": "GeoPlan",
        "description": (
            "Aplicación multiplataforma (Mobile/Desktop) para planificación de viajes "
            "en tiempo real utilizando datos dinámicos. Actualmente en desarrollo."
        ),
        "description_en": (
            "Cross-platform app (Mobile/Desktop) for real-time trip planning "
            "using dynamic data. Currently in development."
        ),
        "tech": ["Python", "C#", "AI Integration"],
        "github_url": "https://github.com/santiagosabadini",
        "live_url": None,
        "featured": True,
        "in_progress": True,
    },
]

skills = [
    {
        "category": "Languages",
        "items": [
            {"name": "Python", "level": "Advanced"},
            {"name": "C#", "level": "Intermediate"},
            {"name": "HTML & CSS", "level": "Basic"},
            {"name": "Java", "level": "Basic"},
        ],
    },
    {
        "category": "AI & Tools",
        "items": [
            {"name": "AI-Assisted Development", "level": "Advanced"},
            {"name": "Architecture Review", "level": "Intermediate"},
            {"name": "Code Optimization", "level": "Intermediate"},
            {"name": "LLM Validation", "level": "Intermediate"},
        ],
    },
    {
        "category": "Development",
        "items": [
            {"name": "Git & GitHub", "level": "Intermediate"},
            {"name": "REST APIs", "level": "Intermediate"},
            {"name": "FastAPI", "level": "Intermediate"},
            {"name": "Discord.py", "level": "Intermediate"},
        ],
    },
]

experience = [
    {
        "id": 1,
        "role": "Recepcionista",
        "company": "—",
        "location": "Bahía Blanca, Argentina",
        "period": "Actualidad",
        "description": (
            "Atención al público y gestión administrativa. "
            "Disponibilidad para trabajo presencial/oficina."
        ),
        "description_en": (
            "Customer service and administrative management. "
            "Available for on-site/office work."
        ),
        "current": True,
    },
]

goals = [
    {
        "title": "Software Architecture Mastery",
        "description": "Dominar la arquitectura de software para supervisar código generado por IA.",
        "description_en": "Master software architecture to oversee AI-generated code.",
        "timeline": "Short-term",
    },
    {
        "title": "International Work Plan",
        "description": "Plan de trabajo internacional en Islandia (2027) utilizando ciudadanía italiana.",
        "description_en": "International work plan in Iceland (2027) using Italian citizenship.",
        "timeline": "2027",
    },
]

contact = {
    "email": "santiagosabadini@email.com",
    "github": "https://github.com/santiagosabadini",
    "linkedin": "https://linkedin.com/in/santiagosabadini",
    "location": "Bahía Blanca, Argentina",
}
