import './About.css'

export default function About({ profile }) {
  return (
    <section id="about">
      <div className="container">
        <h2 className="section-title animate-on-scroll">About Me</h2>

        <div className="about__grid animate-on-scroll">
          <div className="about__text">
            <p>{profile?.bio_en || profile?.bio || ''}</p>
            <p className="about__focus">
              My focus is on integrating AI into the development workflow — optimizing code,
              reviewing architecture, and validating logic generated by language models.
            </p>
          </div>

          <div className="about__details">
            <div className="about__detail">
              <span className="about__label">Location</span>
              <span className="about__value">{profile?.location || 'Bahía Blanca, Argentina'}</span>
            </div>
            <div className="about__detail">
              <span className="about__label">Education</span>
              <span className="about__value">{profile?.education || 'UTN'}</span>
            </div>
            <div className="about__detail">
              <span className="about__label">Focus</span>
              <span className="about__value">Python, C# & AI</span>
            </div>
            <div className="about__detail">
              <span className="about__label">Setup</span>
              <span className="about__value">MacBook Air M1</span>
            </div>
          </div>
        </div>
      </div>
    </section>
  )
}
